### ISSUE TITLE
Where do usernames and passwords for the chat server come from?

### ISSUE THREAD

**Issue by GrandMoff100** [janaSunrise/ZeroCOM#3]
In the documentation you mentioned how the client logs in with a username and password. Does the server create and share those with the client somehow? Or is there somewhere else that the usernames and passwords come from?

**Comment by janaSunrise** [comment]
Basically, the user who creates the server has to add the password in the `config.ini`
Then, The password is hashed using SHA1, or MD5, or SHA256, and the algorithm is sent to the client. The client logs with password, and it's hashed and sent to the server. If the hashes match and the key of the user is valid and exists, He's allowed to login 😁 

For now, This is not ready yet, Will be ready soon, Once #1 issue is fixed with bugs regarding Key verification and buffering.

Here's an example.

I login with 1234 password, and the server sends me the hash algorithm. I hash `1234` with that, and forward to the server. It hashes the password in config, and checks if the hash matches.

Hope you understood.
